name: build and test
on: [push]
jobs:
  just_test:
    if: startsWith(github.ref, 'refs/heads/main')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "^1.19.1"
      - name: go test
        run: go test -v ./...
  test_build_release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "^1.19.1"
      - name: Get the version
        id: get_tag
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: go test
        run: go test -v ./...
      - name: build
        shell: bash
        run: |
          # Make an artifacts directory
          mkdir -p artifacts

          # Run the build for each supported OS using x86_64.
          # Building for windows.
          echo "Building for Windows on amd64..."
          GOOS=$os GOARCH=amd64 CGO_ENABLED=0 go build -a -ldflags="-X main.version=${{ steps.get_tag.outputs.SOURCE_TAG }}" -o ./artifacts/launch_windows.exe .

          # Make an ARM and ARM64 bin for linux and Mac.
          for os in "linux" "darwin"; do
            for arch in "amd64" "arm64" "arm"; do
              echo "Building for $os on $arch..."
              if [ "$os" = "darwin" ] && [ "$arch" = "arm" ]; then
                echo "Skipping $os on $arch..."
                continue
              fi
              GOOS=$os GOARCH=$arch CGO_ENABLED=0 go build -a -ldflags="-X main.version=${{ steps.get_tag.outputs.SOURCE_TAG }}" -o ./artifacts/launch_${os}_${arch} .
            done
          done

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*
          body_path: .github/workflows/release_body.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
